final List<Map<String, String>> itunesCountries = [
  {"code": "ae", "name": "United Arab Emirates"},
  {"code": "ag", "name": "Antigua and Barbuda"},
  {"code": "ai", "name": "Anguilla"},
  {"code": "al", "name": "Albania"},
  {"code": "am", "name": "Armenia"},
  {"code": "ao", "name": "Angola"},
  {"code": "ar", "name": "Argentina"},
  {"code": "at", "name": "Austria"},
  {"code": "au", "name": "Australia"},
  {"code": "az", "name": "Azerbaijan"},
  {"code": "bb", "name": "Barbados"},
  {"code": "be", "name": "Belgium"},
  {"code": "bf", "name": "Burkina-Faso"},
  {"code": "bg", "name": "Bulgaria"},
  {"code": "bh", "name": "Bahrain"},
  {"code": "bj", "name": "Benin"},
  {"code": "bm", "name": "Bermuda"},
  {"code": "bn", "name": "Brunei Darussalam"},
  {"code": "bo", "name": "Bolivia"},
  {"code": "br", "name": "Brazil"},
  {"code": "bs", "name": "Bahamas"},
  {"code": "bt", "name": "Bhutan"},
  {"code": "bw", "name": "Botswana"},
  {"code": "by", "name": "Belarus"},
  {"code": "bz", "name": "Belize"},
  {"code": "ca", "name": "Canada"},
  {"code": "cg", "name": "Democratic Republic of the Congo"},
  {"code": "ch", "name": "Switzerland"},
  {"code": "cl", "name": "Chile"},
  {"code": "cn", "name": "China"},
  {"code": "co", "name": "Colombia"},
  {"code": "cr", "name": "Costa Rica"},
  {"code": "cv", "name": "Cape Verde"},
  {"code": "cy", "name": "Cyprus"},
  {"code": "cz", "name": "Czech Republic"},
  {"code": "de", "name": "Germany"},
  {"code": "dk", "name": "Denmark"},
  {"code": "dm", "name": "Dominica"},
  {"code": "do", "name": "Dominican Republic"},
  {"code": "dz", "name": "Algeria"},
  {"code": "ec", "name": "Ecuador"},
  {"code": "ee", "name": "Estonia"},
  {"code": "eg", "name": "Egypt"},
  {"code": "es", "name": "Spain"},
  {"code": "fi", "name": "Finland"},
  {"code": "fj", "name": "Fiji"},
  {"code": "fm", "name": "Federated States of Micronesia"},
  {"code": "fr", "name": "France"},
  {"code": "gb", "name": "Great Britain"},
  {"code": "gd", "name": "Grenada"},
  {"code": "gh", "name": "Ghana"},
  {"code": "gm", "name": "Gambia"},
  {"code": "gr", "name": "Greece"},
  {"code": "gt", "name": "Guatemala"},
  {"code": "gw", "name": "Guinea Bissau"},
  {"code": "gy", "name": "Guyana"},
  {"code": "hk", "name": "Hong Kong"},
  {"code": "hn", "name": "Honduras"},
  {"code": "hr", "name": "Croatia"},
  {"code": "hu", "name": "Hungaria"},
  {"code": "id", "name": "Indonesia"},
  {"code": "ie", "name": "Ireland"},
  {"code": "il", "name": "Israel"},
  {"code": "in", "name": "India"},
  {"code": "is", "name": "Iceland"},
  {"code": "it", "name": "Italy"},
  {"code": "jm", "name": "Jamaica"},
  {"code": "jo", "name": "Jordan"},
  {"code": "jp", "name": "Japan"},
  {"code": "ke", "name": "Kenya"},
  {"code": "kg", "name": "Krygyzstan"},
  {"code": "kh", "name": "Cambodia"},
  {"code": "kn", "name": "Saint Kitts and Nevis"},
  {"code": "kr", "name": "South Korea"},
  {"code": "kw", "name": "Kuwait"},
  {"code": "ky", "name": "Cayman Islands"},
  {"code": "kz", "name": "Kazakhstan"},
  {"code": "la", "name": "Laos"},
  {"code": "lb", "name": "Lebanon"},
  {"code": "lc", "name": "Saint Lucia"},
  {"code": "lk", "name": "Sri Lanka"},
  {"code": "lr", "name": "Liberia"},
  {"code": "lt", "name": "Lithuania"},
  {"code": "lu", "name": "Luxembourg"},
  {"code": "lv", "name": "Latvia"},
  {"code": "md", "name": "Moldova"},
  {"code": "mg", "name": "Madagascar"},
  {"code": "mk", "name": "Macedonia"},
  {"code": "ml", "name": "Mali"},
  {"code": "mn", "name": "Mongolia"},
  {"code": "mo", "name": "Macau"},
  {"code": "mr", "name": "Mauritania"},
  {"code": "ms", "name": "Montserrat"},
  {"code": "mt", "name": "Malta"},
  {"code": "mu", "name": "Mauritius"},
  {"code": "mw", "name": "Malawi"},
  {"code": "mx", "name": "Mexico"},
  {"code": "my", "name": "Malaysia"},
  {"code": "mz", "name": "Mozambique"},
  {"code": "na", "name": "Namibia"},
  {"code": "ne", "name": "Niger"},
  {"code": "ng", "name": "Nigeria"},
  {"code": "ni", "name": "Nicaragua"},
  {"code": "nl", "name": "Netherlands"},
  {"code": "np", "name": "Nepal"},
  {"code": "no", "name": "Norway"},
  {"code": "nz", "name": "New Zealand"},
  {"code": "om", "name": "Oman"},
  {"code": "pa", "name": "Panama"},
  {"code": "pe", "name": "Peru"},
  {"code": "pg", "name": "Papua New Guinea"},
  {"code": "ph", "name": "Philippines"},
  {"code": "pk", "name": "Pakistan"},
  {"code": "pl", "name": "Poland"},
  {"code": "pt", "name": "Portugal"},
  {"code": "pw", "name": "Palau"},
  {"code": "py", "name": "Paraguay"},
  {"code": "qa", "name": "Qatar"},
  {"code": "ro", "name": "Romania"},
  {"code": "ru", "name": "Russia"},
  {"code": "sa", "name": "Saudi Arabia"},
  {"code": "sb", "name": "Soloman Islands"},
  {"code": "sc", "name": "Seychelles"},
  {"code": "se", "name": "Sweden"},
  {"code": "sg", "name": "Singapore"},
  {"code": "si", "name": "Slovenia"},
  {"code": "sk", "name": "Slovakia"},
  {"code": "sl", "name": "Sierra Leone"},
  {"code": "sn", "name": "Senegal"},
  {"code": "sr", "name": "Suriname"},
  {"code": "st", "name": "Sao Tome e Principe"},
  {"code": "sv", "name": "El Salvador"},
  {"code": "sz", "name": "Swaziland"},
  {"code": "tc", "name": "Turks and Caicos Islands"},
  {"code": "td", "name": "Chad"},
  {"code": "th", "name": "Thailand"},
  {"code": "tj", "name": "Tajikistan"},
  {"code": "tm", "name": "Turkmenistan"},
  {"code": "tn", "name": "Tunisia"},
  {"code": "tr", "name": "Turkey"},
  {"code": "tt", "name": "Republic of Trinidad and Tobago"},
  {"code": "tw", "name": "Taiwan"},
  {"code": "tz", "name": "Tanzania"},
  {"code": "ua", "name": "Ukraine"},
  {"code": "ug", "name": "Uganda"},
  {"code": "us", "name": "United States of America"},
  {"code": "uy", "name": "Uruguay"},
  {"code": "uz", "name": "Uzbekistan"},
  {"code": "vc", "name": "Saint Vincent and the Grenadines"},
  {"code": "ve", "name": "Venezuela"},
  {"code": "vg", "name": "British Virgin Islands"},
  {"code": "vn", "name": "Vietnam"},
  {"code": "ye", "name": "Yemen"},
  {"code": "za", "name": "South Africa"},
  {"code": "zw", "name": "Zimbabwe"}
];
