final List<Map<String, String>> podcastGenres = [
  {"genre": "All", "id": ""},
  {"genre": 'Arts', "id": "1301"},
  {"genre": 'Business', "id": "1321"},
  {"genre": 'Comedy', "id": "1303"},
  {"genre": 'Education', "id": "1304"},
  {"genre": 'Fiction', "id": "1483"},
  {"genre": 'Government', "id": "1511"},
  {"genre": 'Health & Fitness', "id": "1512"},
  {"genre": 'History', "id": "1487"},
  {"genre": 'Kids & Family', "id": "1305"},
  {"genre": 'Leisure', "id": "1502"},
  {"genre": 'Music', "id": "1310"},
  {"genre": 'News', "id": "1489"},
  {"genre": 'Religion & Spirituality', "id": "1314"},
  {"genre": 'Science', "id": "1533"},
  {"genre": 'Society & Culture', "id": "1324"},
  {"genre": 'Sports', "id": "1545"},
  {"genre": 'TV & Film', "id": "1309"},
  {"genre": 'Technology', "id": "1318"},
  {"genre": 'True Crime', "id": "1488"},
];

final List<Map<String, String>> podcastIndexGenres = [
  {"genre": "Arts", "id": "1301"},
  {"genre": "Books", "id": "1482"},
  {"genre": "Design", "id": "1402"},
  {"genre": "Fashion & Beauty", "id": "1459"},
  {"genre": "Food", "id": "1306"},
  {"genre": "Performing Arts", "id": "1405"},
  {"genre": "Visual Arts", "id": "1406"},
  {"genre": "Business", "id": "1321"},
  {"genre": "Careers", "id": "1410"},
  {"genre": "Entrepreneurship", "id": "1493"},
  {"genre": "Investing", "id": "1412"},
  {"genre": "Management", "id": "1413"},
  {"genre": "Marketing", "id": "1414"},
  {"genre": "Non-Profit", "id": "1415"},
  {"genre": "Comedy", "id": "1303"},
  {"genre": "Comedy Interviews", "id": "1496"},
  {"genre": "Improv", "id": "1495"},
  {"genre": "Stand-Up", "id": "1498"},
  {"genre": "Education", "id": "1304"},
  {"genre": "Courses", "id": "1499"},
  {"genre": "How To", "id": "1501"},
  {"genre": "Language Learning", "id": "1505"},
  {"genre": "Self-Improvement", "id": "1500"},
  {"genre": "Fiction", "id": "1483"},
  {"genre": "Comedy Fiction", "id": "1485"},
  {"genre": "Drama", "id": "1489"},
  {"genre": "Science Fiction", "id": "1488"},
  {"genre": "Government", "id": "1511"},
  {"genre": "History", "id": "1487"},
  {"genre": "Health & Fitness", "id": "1307"},
  {"genre": "Alternative Health", "id": "1481"},
  {"genre": "Fitness", "id": "1417"},
  {"genre": "Medicine", "id": "1418"},
  {"genre": "Mental Health", "id": "1420"},
  {"genre": "Nutrition", "id": "1421"},
  {"genre": "Sexuality", "id": "1421"},
  {"genre": "Kids & Family", "id": "1305"},
  {"genre": "Education for Kids", "id": "1516"},
  {"genre": "Parenting", "id": "1101"},
  {"genre": "Pets & Animals", "id": "1100"},
  {"genre": "Stories for Kids", "id": "1519"},
  {"genre": "Leisure", "id": "1502"},
  {"genre": "Animation & Manga", "id": "1461"},
  {"genre": "Automotive", "id": "1503"},
  {"genre": "Aviation", "id": "1506"},
  {"genre": "Crafts", "id": "1507"},
  {"genre": "Games", "id": "1404"},
  {"genre": "Hobbies", "id": "1460"},
  {"genre": "Home & Garden", "id": "1544"},
  {"genre": "Video Games", "id": "1404"},
  {"genre": "Music", "id": "1310"},
  {"genre": "Music Commentary", "id": "1536"},
  {"genre": "Music History", "id": "1537"},
  {"genre": "Music Interviews", "id": "1538"},
  {"genre": "News", "id": "1489"},
  {"genre": "Business News", "id": "1490"},
  {"genre": "Daily News", "id": "1526"},
  {"genre": "Entertainment News", "id": "1525"},
  {"genre": "News Commentary", "id": "1494"},
  {"genre": "Politics", "id": "1527"},
  {"genre": "Sports News", "id": "1492"},
  {"genre": "Tech News", "id": "1528"},
  {"genre": "Religion & Spirituality", "id": "1314"},
  {"genre": "Buddhism", "id": "1438"},
  {"genre": "Christianity", "id": "1439"},
  {"genre": "Hinduism", "id": "1463"},
  {"genre": "Islam", "id": "1440"},
  {"genre": "Judaism", "id": "1441"},
  {"genre": "Religion", "id": "1444"},
  {"genre": "Spirituality", "id": "1445"},
  {"genre": "Science", "id": "1533"},
  {"genre": "Astronomy", "id": "1540"},
  {"genre": "Chemistry", "id": "1541"},
  {"genre": "Earth Sciences", "id": "1542"},
  {"genre": "Life Sciences", "id": "1543"},
  {"genre": "Mathematics", "id": "1544"},
  {"genre": "Natural Sciences", "id": "1545"},
  {"genre": "Nature", "id": "1477"},
  {"genre": "Physics", "id": "1546"},
  {"genre": "Social Sciences", "id": "1547"},
  {"genre": "Society & Culture", "id": "1324"},
  {"genre": "Documentary", "id": "1543"},
  {"genre": "Personal Journals", "id": "1302"},
  {"genre": "Philosophy", "id": "1443"},
  {"genre": "Places & Travel", "id": "1320"},
  {"genre": "Relationships", "id": "1426"},
  {"genre": "Sports", "id": "1545"},
  {"genre": "Baseball", "id": "1546"},
  {"genre": "Basketball", "id": "1547"},
  {"genre": "Cricket", "id": "1548"},
  {"genre": "Fantasy Sports", "id": "1552"},
  {"genre": "Football", "id": "1553"},
  {"genre": "Golf", "id": "1554"},
  {"genre": "Hockey", "id": "1555"},
  {"genre": "Rugby", "id": "1556"},
  {"genre": "Running", "id": "1557"},
  {"genre": "Soccer", "id": "1558"},
  {"genre": "Swimming", "id": "1559"},
  {"genre": "Tennis", "id": "1560"},
  {"genre": "Volleyball", "id": "1561"},
  {"genre": "Wilderness", "id": "1562"},
  {"genre": "Wrestling", "id": "1563"},
  {"genre": "Technology", "id": "1318"},
  {"genre": "True Crime", "id": "1488"},
  {"genre": "TV & Film", "id": "1309"},
  {"genre": "After Shows", "id": "1564"},
  {"genre": "Film History", "id": "1565"},
  {"genre": "Film Interviews", "id": "1566"},
  {"genre": "Film Reviews", "id": "1567"},
  {"genre": "TV Reviews", "id": "1569"}
];
